#!/usr/bin/env python

import datetime

data_dict = {
    0: {
            'name':        'Sun',
            'radius':      1392000./2,
            'label':       datetime.datetime(2000, 10, 1, 0, 0),
            'pages':       [1],
            'fill_color':  'yellow',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 0,
            'satellite' : 0,
            'sdate' : datetime.datetime(2000,1,1),
            'edate' : datetime.datetime(2000,2,1),
            'interval' : [1, 'h'],
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    199: {
            'name':        'Mercury',
            'radius':      4880./2,
            'label':       datetime.datetime(2000, 10, 16, 0, 0),
            'pages':       [2, 3],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 199,
            'satellite' : 199,
            'sdate' : datetime.datetime(2000,10,1),
            'edate' : datetime.datetime(2000,11,1),
            'interval' : [1, 'h'],
            'zoom': 1,
            'perihelion': 4.60E7,
            'aphelion':   6.98E7,
            'tide_locked': True,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    299: {
            'name':        'Venus',
            'radius':      12104./2,
            'label':       datetime.datetime(2000, 4, 10, 0, 0),
            'pages':       [4],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 299,
            'satellite' : 299,
            'sdate' : datetime.datetime(2000,3,1),
            'edate' : datetime.datetime(2000,5,1),
            'interval' : [1, 'h'],
            'zoom': 1,
            'perihelion': 1.075E8,
            'aphelion':   1.089E8,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    399: {
            'name':        'Earth',
            'radius':      12742./2,
            'label':       datetime.datetime(2000, 8, 28, 0, 0),
            'pages':       [5],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 399,
            'satellite' : 399,
            'sdate' : datetime.datetime(2000,8,1),
            'edate' : datetime.datetime(2000,10,1),
            'interval' : [1, 'h'],
            'zoom': 1,
            'perihelion': 1.471E8,
            'aphelion':   1.521E8,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    301: {
            'name':        'Moon',
            'radius':      1737.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [5],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 399,
            'satellite' : 301,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    499: {
            'name':        'Mars',
            'radius':      6780./2,
            'label':       datetime.datetime(1999, 11, 22, 0, 0),
            'pages':       [7, 8],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 499,
            'satellite' : 499,
            'sdate' : datetime.datetime(1999,11,1),
            'edate' : datetime.datetime(2000,1,1),
            'interval' : [1, 'h'],
            'zoom': 1,
            'perihelion': 2.066E8,
            'aphelion':   2.492E8,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    401: {
            'name':        'Phobos',
            'radius':      7.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [7, 8],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 499,
            'satellite' : 401,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    402: {
            'name':        'Deimos',
            'radius':      12.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [7, 8],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 499,
            'satellite' : 402,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    599: {
            'name':        'Jupiter',
            'radius':      139822./2,
            'label':       datetime.datetime(1998, 1, 12, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 599,
            'sdate' : datetime.datetime(1997,12,1),
            'edate' : datetime.datetime(1998,3,1),
            'interval' : [6, 'm'],
            'zoom': 1,
            'perihelion': 7.406E8,
            'aphelion':   8.160E8,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    501: {
            'name':        'Io',
            'radius':      1821.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 501,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    502: {
            'name':        'Europa',
            'radius':      1565.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 502,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    503: {
            'name':        'Ganymede',
            'radius':      2634.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 503,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    504: {
            'name':        'Callisto',
            'radius':      2403.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 504,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    505: {
            'name':        'Amalthea',
            'radius':      100.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 505,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'right',
           },
    506: {
            'name':        'Himalia',
            'radius':      85.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 506,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    507: {
            'name':        'Elara',
            'radius':      40.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 507,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    508: {
            'name':        'Pasiphae',
            'radius':      18.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 508,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    509: {
            'name':        'Sinope',
            'radius':      14.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [20, 21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 509,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    510: {
            'name':        'Lysithea',
            'radius':      12.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 510,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    511: {
            'name':        'Carme',
            'radius':      15.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 511,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    512: {
            'name':        'Ananke',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 512,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    513: {
            'name':        'Leda',
            'radius':      5.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 513,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    514: {
            'name':        'Thebe',
            'radius':      50.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 514,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'top',
            'horizontalalignment': 'left',
           },
    515: {
            'name':        'Adrastea',
            'radius':      9.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 515,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    516: {
            'name':        'Metis',
            'radius':      21.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 516,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    517: {
            'name':        'Callirrhoe',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 517,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    518: {
            'name':        'Themisto',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [21, 22],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 599,
            'satellite' : 518,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    699: {
            'name':        'Saturn',
            'radius':      116464./2,
            'label':       datetime.datetime(1993, 12, 6, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 699,
            'sdate' : datetime.datetime(1993,11,1),
            'edate' : datetime.datetime(1994,2,1),
            'interval' : [10, 'm'],
            'zoom': 1,
            'perihelion': 1.3476E9,
            'aphelion':   1.5064E9,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    601: {
            'name':        'Mimas',
            'radius':      200.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 601,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    602: {
            'name':        'Enceladus',
            'radius':      247.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 602,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'top',
            'horizontalalignment': 'right',
           },
    603: {
            'name':        'Tethys',
            'radius':      530.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 603,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'center',
            'horizontalalignment': 'right',
           },
    604: {
            'name':        'Dione',
            'radius':      560.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 604,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'right',
           },
    605: {
            'name':        'Rhea',
            'radius':      560.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 605,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'top',
            'horizontalalignment': 'right',
           },
    606: {
            'name':        'Titan',
            'radius':      2575.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 606,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'top',
            'horizontalalignment': 'right',
           },
    607: {
            'name':        'Hyperion',
            'radius':      150.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 607,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'right',
           },
    608: {
            'name':        'Iapetus',
            'radius':      718.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 608,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    609: {
            'name':        'Phoebe',
            'radius':      110.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 609,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    610: {
            'name':        'Janus',
            'radius':      95.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 610,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    611: {
            'name':        'Epimetheus',
            'radius':      58.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 611,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    612: {
            'name':        'Helene',
            'radius':      16.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 612,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    613: {
            'name':        'Telesto',
            'radius':      12.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 613,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'top',
            'horizontalalignment': 'right',
           },
    614: {
            'name':        'Calypso',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 614,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    615: {
            'name':        'Atlas',
            'radius':      15.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 615,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    616: {
            'name':        'Prometheus',
            'radius':      50.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 616,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    617: {
            'name':        'Pandora',
            'radius':      45.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [39, 40, 41],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 699,
            'satellite' : 617,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'top',
            'horizontalalignment': 'right',
           },
    799: {
            'name':        'Uranus',
            'radius':      50724./2,
            'label':       datetime.datetime(2003, 7, 21, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 799,
            'sdate' : datetime.datetime(2003,5,1),
            'edate' : datetime.datetime(2003,11,1),
            'interval' : [10, 'm'],
            'zoom': 1,
            'perihelion': 2.734E9,
            'aphelion':   3.0052E9,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    701: {
            'name':        'Ariel',
            'radius':      580.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 701,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    702: {
            'name':        'Umbriel',
            'radius':      580.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 702,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    703: {
            'name':        'Titania',
            'radius':      788.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 703,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    704: {
            'name':        'Oberon',
            'radius':      761.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 704,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    705: {
            'name':        'Miranda',
            'radius':      240.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 705,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    706: {
            'name':        'Cordelia',
            'radius':      13.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 706,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    707: {
            'name':        'Ophelia',
            'radius':      15.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 707,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    708: {
            'name':        'Bianca',
            'radius':      21.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 708,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    709: {
            'name':        'Cressida',
            'radius':      31.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 709,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    710: {
            'name':        'Desdemona',
            'radius':      27.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 710,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    711: {
            'name':        'Juliet',
            'radius':      42.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 711,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    712: {
            'name':        'Portia',
            'radius':      54.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 712,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    713: {
            'name':        'Rosalind',
            'radius':      27.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 713,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    714: {
            'name':        'Belinda',
            'radius':      33.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 714,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    715: {
            'name':        'Puck',
            'radius':      77.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 715,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    716: {
            'name':        'Caliban',
            'radius':      30.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 716,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'right',
           },
    717: {
            'name':        'Sycorax',
            'radius':      60.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 717,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    718: {
            'name':        'Prospero',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 718,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    719: {
            'name':        'Setebos',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 719,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    720: {
            'name':        'Stephano',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 720,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    721: {
            'name':        'Trinculo',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 721,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    722: {
            'name':        'Francisco',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 722,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    723: {
            'name':        'Margaret',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 723,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'right',
           },
    724: {
            'name':        'Ferdinand',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [81],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 799,
            'satellite' : 724,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    899: {
            'name':        'Neptune',
            'radius':      49248./2,
            'label':       datetime.datetime(2011, 12, 26, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 899,
            'sdate' : datetime.datetime(2011,10,1),
            'edate' : datetime.datetime(2012,6,1),
            'interval' : [10, 'm'],
            'zoom': 1,
            'perihelion': 4.4580E9,
            'aphelion':   4.5352E9,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    801: {
            'name':        'Triton',
            'radius':      1352.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 801,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 10,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    802: {
            'name':        'Nereid',
            'radius':      170.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 802,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    803: {
            'name':        'Naiad',
            'radius':      29.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 803,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'right',
           },
    804: {
            'name':        'Thalassa',
            'radius':      40.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 804,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    805: {
            'name':        'Despina',
            'radius':      74.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 805,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    806: {
            'name':        'Galatea',
            'radius':      79.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 806,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    807: {
            'name':        'Larissa',
            'radius':      96.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 807,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    808: {
            'name':        'Proteus',
            'radius':      208.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 808,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    809: {
            'name':        '2002N1',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 809,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    810: {
            'name':        '2002N2',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 810,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    811: {
            'name':        '2002N3',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 811,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    812: {
            'name':        '2003N1',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 812,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    813: {
            'name':        '2002N4',
            'radius':      10.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [121],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 899,
            'satellite' : 813,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 1,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    999: {
            'name':        'Pluto',
            'radius':      2274./2,
            'label':       datetime.datetime(2043, 12, 28, 0, 0),
            'pages':       [161],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 999,
            'satellite' : 999,
            'sdate' : datetime.datetime(2043,11,1),
            'edate' : datetime.datetime(2044,4,1),
            'interval' : [1, 'd'],
            'zoom': 1,
            'perihelion': 4.4458E9,
            'aphelion':   7.3812E9,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
    901: {
            'name':        'Charon',
            'radius':      593.,
            'label':       datetime.datetime(2000, 8, 29, 0, 0),
            'pages':       [161],
            'fill_color':  'black',
            'orbit_color': 'black',
            'line_style':   '-',
            'line_width': 0.1,
            'line_dashscale': 0.1,
            'target' : 999,
            'satellite' : 901,
            'sdate' : None,
            'edate' : None,
            'interval' : None,
            'zoom': 100,
            'verticalalignment': 'bottom',
            'horizontalalignment': 'left',
           },
#    10204: {
#            'name':        'CONTOUR-A Spacecraft fragment',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10204,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10205: {
#            'name':        'CONTOUR-B Spacecraft fragment',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10205,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10206: {
#            'name':        'CONTOUR-C Spacecraft fragment',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10206,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10150: {
#            'name':        'Cassini-Huygens Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10150,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10151: {
#            'name':        'Chandra Observatory',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10151,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10140: {
#            'name':        'Deep Impact Flyby',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10140,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10070: {
#            'name':        'Deep Impact IMPACTOR',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10070,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10030: {
#            'name':        'Deep Space 1 Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10030,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10344: {
#            'name':        'Galileo Probe',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10344,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10077: {
#            'name':        'Galileo Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10077,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    47900: {
#            'name':        'Genesis (SRC) Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 47900,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10047: {
#            'name':        'Genesis (bus) Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10047,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10078: {
#            'name':        'Giotto Spacecraft Flyby',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10078,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10130: {
#            'name':        'Hayabusa Spacecraft (Muses-C)',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10130,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10486: {
#            'name':        'Herschel Space Observatory',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10486,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10048: {
#            'name':        'Hubble Space Telescope',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10048,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10198: {
#            'name':        'INTEGRAL Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10198,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10064: {
#            'name':        'Infrared Space Observatory',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10064,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10025: {
#            'name':        'Lunar Prospector Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10025,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10236: {
#            'name':        'Messenger Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10236,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10041: {
#            'name':        'Mars Express Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10041,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    74900: {
#            'name':        'MRO Centaur Stage Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 74900,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10053: {
#            'name':        'Mars Odyssey Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10053,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10074: {
#            'name':        'Mars Reconnaissance Orbiter Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10074,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10093: {
#            'name':        'NEAR Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10093,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10997: {
#            'name':        'NEOCP 6Q0B44E',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
##            'line_style':   '-',
#            'line_width': 0.1,
##            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10997,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10996: {
#            'name':        'NEOCP 6R10D99',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10996,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10998: {
#            'name':        'NEOCP J002E3',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10998,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10178: {
#            'name':        'New Horizons Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10178,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10098: {
#            'name':        'Nozomi Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10098,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10253: {
#            'name':        'Opportunity Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10253,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10023: {
#            'name':        'Pioneer 10',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10023,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10024: {
#            'name':        'Pioneer 11',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10024,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10006: {
#            'name':        'Pioneer 6',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10006,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10489: {
#            'name':        'Plank Space Observatory',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10489,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10226: {
#            'name':        'Rosetta Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10226,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    234900: {
#            'name':        'STEREO Third Stage',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 234900,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10234: {
#            'name':        'STEREO-A Spacecraft (AHEAD)',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10234,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10235: {
#            'name':        'STEREO-B Spacecraft (BEHIND)',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10235,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10254: {
#            'name':        'Spirit Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10254,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10079: {
#            'name':        'Spitzer Space Telescope',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10079,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    29900: {
#            'name':        'Stardust Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 29900,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10029: {
#            'name':        'Stardust Bus Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10029,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10055: {
#            'name':        'Ulysses Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10055,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [1, 'd'],
#            'zoom': 1,
#           },
#    10248: {
#            'name':        'Venus Express Spacecraft',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10248,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10031: {
#            'name':        'Voyager I',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10031,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
#    10032: {
#            'name':        'Voyager II',
#            'radius':      0.01,
#            'label':       datetime.datetime(2043, 12, 25, 0, 0),
#            'pages':       [161],
#            'fill_color':  'black',
#            'orbit_color': 'black',
#            'line_style':   '-',
#            'line_width': 0.1,
#            'line_dashscale': 0.1,
#            'target' : -1,
#            'satellite' : 10032,
#            'sdate' : None,
#            'edate' : None,
#            'interval' : [2, 'd'],
#            'zoom': 1,
#           },
}
label_dict = {
              'Sun'    :(1392000./2, datetime.datetime(2000, 1, 1, 0, 0)),
              'Mercury':(4880./2, datetime.datetime(2000, 10, 17, 0, 0)),
              'Venus'  :(12104./2, datetime.datetime(2000, 4, 7, 0, 0)),
              'Earth'  :(12742./2,  datetime.datetime(2000, 8, 29, 0, 0)),
              'Mars'   :(6780./2,  datetime.datetime(1999, 11, 18, 0, 0)),
              'Jupiter':(139822./2,  datetime.datetime(1998, 1, 7, 0, 0)),
              'Saturn' :(116464./2,  datetime.datetime(1993, 11, 25, 0, 0)),
              'Uranus' :(50724./2,  datetime.datetime(2003, 7, 9, 22, 0)),
              'Neptune':(49248./2,  datetime.datetime(2011, 12, 15, 0, 0)),
              'Pluto'  :(2274./2,  datetime.datetime(2043, 12, 25, 0, 0)),
    'CONTOUR-A Spacecraft fragment' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'CONTOUR-B Spacecraft fragment' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'CONTOUR-C Spacecraft fragment' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Cassini-Huygens Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Cassini Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Chandra Observatory' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Deep Impact Flyby' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Deep Impact IMPACTOR' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Deep Space 1 Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Galileo Probe' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Galileo Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Genesis (SRC) Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Genesis (bus) Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Giotto Spacecraft Flyby' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Hayabusa Spacecraft (Muses-C)' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Herschel Space Observatory (Spacecraft)' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Hubble Space Telescope' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'INTEGRAL Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Infrared Space Observatory' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Lunar Prospector Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Messenger Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'MRO Centaur Stage Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Mars Express Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Mars Odyssey Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Mars Reconnaissance Orbiter Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'NEAR Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'NEOCP 6Q0B44E' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'NEOCP 6R10D99' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'NEOCP J002E3' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'New Horizons Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Nozomi Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Opportunity Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Pioneer 10' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Pioneer 11' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Pioneer 6' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Pioneer 8' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Plank Space Observatory Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Rosetta Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'STEREO Third Stage Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'STEREO-A Spacecraft (AHEAD)' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'STEREO-B Spacecraft (BEHIND)' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Spirit Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Spitzer Space Telescope' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Stardust Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Stardust Bus Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Ulysses Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Venus Express Spacecraft' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Voyager I' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
    'Voyager II' : (1, datetime.datetime(2043, 12, 25, 0, 0)),
             }



color_table = [
                        'red',
                        'orange',
                        'yellow',
                        'green',
                        'blue',
                        'darkblue',
                        'purple',
                  ]


sat_dict = { 
            ("Earth", 1, "Moon"): (1737, 10),
            ("Mars", 1, "Phobos"): (7, 100),
            ("Mars", 2, "Deimos"): (12, 100),
            ("Jupiter", 1, "Io"): (1821, 10),
            ("Jupiter", 2, "Europa"): (1565, 10),
            ("Jupiter", 3, "Ganymede"): (2634, 10),
            ("Jupiter", 4, "Callisto"): (2403, 10),
            ("Jupiter", 5, "Amalthea"): (100, 10),
            ("Jupiter", 6, "Himalia"): (85, 1),
            ("Jupiter", 7, "Elara"): (40, 1),
            ("Jupiter", 8, "Pasiphae"): (18, 1),
            ("Jupiter", 9, "Sinope"): (14, 1),
            ("Jupiter", 10, "Lysithea"): (12, 1),
            ("Jupiter", 11, "Carme"): (15, 1),
            ("Jupiter", 12, "Ananke"): (10, 1),
            ("Jupiter", 13, "Leda"): (5, 1),
            ("Jupiter", 14, "Thebe"): (50, 10),
            ("Jupiter", 15, "Adrastea"): (9, 100),
            ("Jupiter", 16, "Metis"): (21, 10),
            ("Jupiter", 17, "Callirrhoe"): (10, 1),
            ("Jupiter", 18, "Themisto"): (10, 1),
            ("Saturn", 1, "Mimas"): (200, 10),
            ("Saturn", 2, "Enceladus"): (247, 10),
            ("Saturn", 3, "Tethys"): (530, 10),
            ("Saturn", 4, "Dione"): (560, 10),
            ("Saturn", 5, "Rhea"): (764, 10),
            ("Saturn", 6, "Titan"): (2575, 1),
            ("Saturn", 7, "Hyperion"): (150, 10),
            ("Saturn", 8, "Iapetus"): (718, 1),
            ("Saturn", 9, "Phoebe"): (110, 1),
            ("Saturn", 10, "Janus"): (95, 100),
            ("Saturn", 11, "Epimetheus"): (58, 100),
            ("Saturn", 12, "Helene"): (16, 10),
            ("Saturn", 13, "Telesto"): (12, 10),
            ("Saturn", 14, "Calypso"): (10, 10),
            ("Saturn", 15, "Atlas"): (15, 10),
            ("Saturn", 16, "Prometheus"): (50, 10),
            ("Saturn", 17, "Pandora"): (45, 100),
            ("Uranus", 1, "Ariel"): (580, 10),
            ("Uranus", 2, "Umbriel"): (580, 100),
            ("Uranus", 3, "Titania"): (788, 10),
            ("Uranus", 4, "Oberon"): (761, 10),
            ("Uranus", 5, "Miranda"): (240, 100),
            ("Uranus", 6, "Cordelia"): (13, 100),
            ("Uranus", 7, "Ophelia"): (15, 100),
            ("Uranus", 8, "Bianca"): (21, 100),
            ("Uranus", 9, "Cressida"): (31, 100),
            ("Uranus", 10, "Desdemona"): (27, 100),
            ("Uranus", 11, "Juliet"): (42, 100),
            ("Uranus", 12, "Portia"): (54, 100),
            ("Uranus", 13, "Rosalind"): (27, 100),
            ("Uranus", 14, "Belinda"): (33, 100),
            ("Uranus", 15, "Puck"): (77, 100),
            ("Uranus", 16, "Caliban"): (30, 1),
            ("Uranus", 17, "Sycorax"): (60, 1),
            ("Uranus", 18, "Prospero"): (10, 1),
            ("Uranus", 19, "Setebos"): (10, 1),
            ("Uranus", 20, "Stephano"): (10, 1),
            ("Uranus", 21, "Trinculo"): (10, 1),
            ("Uranus", 22, "Francisco"): (10, 1),
            ("Uranus", 23, "Margaret"): (10, 1),
            ("Uranus", 24, "Ferdinand"): (10, 1),
            ("Neptune", 1, "Triton"): (1352, 10),
            ("Neptune", 2, "Nereid"): (170, 1),
            ("Neptune", 3, "Naiad"): (29, 100),
            ("Neptune", 4, "Thalassa"): (40, 100),
            ("Neptune", 5, "Despina"): (74, 100),
            ("Neptune", 6, "Galatea"): (79, 100),
            ("Neptune", 7, "Larissa"): (96, 100),
            ("Neptune", 8, "Proteus"): (208, 100),
            ("Neptune", 9, "2002N1"): (10, 1),
            ("Neptune", 10, "2002N2"): (10, 1),
            ("Neptune", 11, "2002N3"): (10, 1),
            ("Neptune", 12, "2003N1"): (10, 1),
            ("Neptune", 13, "2002N4"): (10, 1),
            ("Pluto", 1, "Charon"): (593, 100),
           }

